#!/bin/bash
#
# Android SDK Environment Variables for Tonnet Mobile
#
# Usage:
#   source scripts/env.sh
#
# For permanent setup, add to your ~/.bashrc or ~/.zshrc:
#   source /path/to/tonnet-mobile/scripts/env.sh
#

# Load machine-specific paths generated by setup-android-sdk.sh. The local file is ignored by Git
# and only provides fallbacks; variables already exported by the caller remain authoritative.
ENV_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_LOCAL_FILE="$ENV_SCRIPT_DIR/env.local.sh"
if [[ -f "$ENV_LOCAL_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$ENV_LOCAL_FILE"
fi
unset ENV_LOCAL_FILE ENV_SCRIPT_DIR

# =============================================================================
# Android SDK Configuration
# =============================================================================

# ANDROID_HOME is canonical; ANDROID_SDK_ROOT is kept for tool compatibility.
export ANDROID_HOME="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-${TONNET_ANDROID_SDK_ROOT:-$HOME/Android/Sdk}}}"
export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-$ANDROID_HOME}"

# Pinned NDK used by Gradle and scripts/build-ton-proxy.sh.
export ANDROID_NDK_HOME="${ANDROID_NDK_HOME:-${TONNET_ANDROID_NDK_ROOT:-$ANDROID_HOME/ndk/27.1.12297006}}"

# Alternative NDK variable (some tools use this)
export NDK_HOME="$ANDROID_NDK_HOME"
unset TONNET_ANDROID_NDK_ROOT TONNET_ANDROID_SDK_ROOT

# =============================================================================
# PATH Configuration
# =============================================================================

# Add SDK tools to PATH (order matters - more specific first)
# cmdline-tools: sdkmanager, avdmanager, etc.
export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"

# platform-tools: adb, fastboot
export PATH="$ANDROID_SDK_ROOT/platform-tools:$PATH"

# emulator
export PATH="$ANDROID_SDK_ROOT/emulator:$PATH"

# build-tools (for aapt, zipalign, etc.)
export PATH="$ANDROID_SDK_ROOT/build-tools/36.0.0:$PATH"

# =============================================================================
# Java Configuration
# =============================================================================

# JDK 21 is required by the Android build.
if [ -z "${JAVA_HOME:-}" ] && [ -d "/usr/lib/jvm/java-21-openjdk" ]; then
    export JAVA_HOME="/usr/lib/jvm/java-21-openjdk"
    export PATH="$JAVA_HOME/bin:$PATH"
fi

# =============================================================================
# Verification Functions
# =============================================================================

# Function to verify Android SDK setup
verify_android_sdk() {
    echo "Android SDK Configuration:"
    echo "  ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
    echo "  ANDROID_HOME:     $ANDROID_HOME"
    echo "  ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
    echo ""

    if [ -d "$ANDROID_SDK_ROOT" ]; then
        echo "SDK Status: OK"
    else
        echo "SDK Status: NOT FOUND"
        return 1
    fi

    if [ -d "$ANDROID_NDK_HOME" ]; then
        echo "NDK Status: OK"
    else
        echo "NDK Status: NOT FOUND (run: sdkmanager 'ndk;27.1.12297006')"
    fi

    echo ""
    echo "Available tools:"
    command -v sdkmanager &> /dev/null && echo "  sdkmanager: $(command -v sdkmanager)"
    command -v adb &> /dev/null && echo "  adb:        $(command -v adb)"
    command -v avdmanager &> /dev/null && echo "  avdmanager: $(command -v avdmanager)"
    command -v emulator &> /dev/null && echo "  emulator:   $(command -v emulator)"
}

# Export the function for interactive use
export -f verify_android_sdk 2>/dev/null || true

# =============================================================================
# Auto-verification (optional - comment out for faster shell startup)
# =============================================================================

# Uncomment to verify SDK on every source:
# verify_android_sdk
